### ISSUE TITLE
Elegir/revisar código de conducta

### ISSUE THREAD

**Issue by lupomontero** [peru-dev/peru-dev.org#6]
Por ahora, en el [`README.md`](https://github.com/peru-dev/peru-dev.org#principios) hacemos referencia a https://es.confcodeofconduct.com/, que lo hemos heredado/reciclado de @lima-js, que a su vez lo adoptó de una traducción del código de conducta de JS Conf en 2012. Este código de conducta esta bueno para eventos, pero quizás no sea tan _adecuado_ para el caso de Perú Dev, que no es exactamente un evento o conferencia, si no una _comunidad de comunidades_... :thinking: 

@techfano [compartió](https://github.com/peru-dev/peru-dev.org/pull/2#pullrequestreview-234158504) como referencia el [código de conducta](https://github.com/colombia-dev/codigo-de-conducta)  de @colombia-dev, y me parece súper interesante por varios motivos... está en español y está pensada para una iniciativa en la que nos estamos inspirando, y podríamos contribuir de vuelta :wink: 

Qué les parecería _adoptar_ el [código de conducta de Combia Dev](https://github.com/colombia-dev/codigo-de-conducta)? Se trata de uno de los pilares de la iniciativa, así que creo que vale la pena que lo leamos y tomemos una decisión informada.

cc/ @AngelFQC @ccarruitero @JoshDev1205 @lizzie136 @MaiaRojas @RuthMeryCardenas @RuthSalvador @talueses @wixo @Xpktro @VikyAle

**Comment by AngelFQC** [comment]
Hola
También podemos revisar las [Pautas para la participación en la comunidad](https://www.mozilla.org/es-ES/about/governance/policies/participation/) de Mozilla

**Comment by lupomontero** [comment]
Hola @AngelFQC, gracias por compartir. Muy buena referencia!

Qué cosas crees que podría tomarse de las _pautas de participación de Mozilla_ para complementar el código de conducta de Colombia Dev?

Quién se anima leer los docs ver los detalles? Yo los he visto por encima, superficialmente, pero quizás alguien más se anima a entrar en los detalles...

**Comment by techfano** [comment]
Hola yo podría en la noche ir revisando también, a ver en que los puedo ayudar a aportar entre ambos documentos. Saludos :)

**Comment by AngelFQC** [comment]
En comportamiento no deseado, el código de conducta de mozilla indica  "... si no estás seguro si una palabra es despectiva, no la uses", y que tampoco está permitido que se trate de influir en otro para realizar comportamientos inaceptables.

**Comment by ccarruitero** [comment]
He revisado un poco el código de conducta de colombia-dev y las pautas de participación de mozilla.

Lo de mozilla me parece bien detallado pero muy extenso, por lo que sugeriria tomar como punto de partida lo de colombia-dev y ver de ir mejorandolo. En mi opinión hay algunos textos que se podrian modificar como lo que menciona "negocios de la comunidad" por algo como "actividades de la comunidad" y algunos fraseos más.

Si se pudiera mantener un código de conducta en conjunto seria ideal, pero habria que ver de mantener los links de contacto fuera del documento y como seria reutilizado. Como es un markdown tal vez se podria hacer con un jekyll, aunque hay que conversarlo.

Como mencionan en el código de conducta de colombia-dev, es una adaptación/traducción del de [Stumptown Syndicate](https://github.com/stumpsyn/policies/blob/master/citizen_code_of_conduct.md), revisando este último he visto que han agregado una sección de politica de armas y han modificado algunos textos en las secciones que tal vez sea bueno tomar en cuenta también.

**Comment by ccarruitero** [comment]
Acabo de notar que en berlin tienen un [código de conducta](http://berlincodeofconduct.org/) muy parecido, si no es el mismo, al de Stumptown Syndicate. Lo tienen [localizado](https://github.com/rubyberlin/code-of-conduct/tree/master/source/localizable) en varios idiomas y puedes [agregarte a la lista de supporters con un PR](https://github.com/rubyberlin/code-of-conduct).

**Comment by lupomontero** [comment]
En el hangout de ayer acordamos _forkear_ el código de conducta de @colombia-dev, y tomarlo como punto de partida sobre el que considerar cambios. He procedido con el fork.

He dejado abierto un PR en ese repo (el fork) con los cambios mínimos que habría que hacer (y dependencias) para que podamos formalmente _adoptar_ el código de conducta:

https://github.com/peru-dev/codigo-de-conducta/pull/1

Les parece si continuamos estas conversaciones en ese repo?

**Comment by lupomontero** [comment]
Ya se aprobó e integró [el PR en el repo de codigo de conducta](https://github.com/peru-dev/codigo-de-conducta) y se [actualizó el `README.md` de este repo](https://github.com/peru-dev/peru-dev.org/pull/11).

Cierro este issue y continuamos la conversación en [`peru-dev/codigo-de-conducta`](https://github.com/peru-dev/codigo-de-conducta).
